version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t amazon-ecs-sample .
      - docker tag amazon-ecs-sample 175471962215.dkr.ecr.ap-southeast-1.amazonaws.com/amazon-ecs-sample:testcodebuild      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 175471962215.dkr.ecr.ap-southeast-1.amazonaws.com/amazon-ecs-sample:testcodebuild
      - echo test kubernetes