version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t amazon-ecs-sample .
      - docker tag amazon-ecs-sample $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/amazon-ecs-sample:testcodebuild      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/amazon-ecs-sample:testcodebuild
      - echo test kubernetes
      - aws configure set aws_access_key_id $aws_access_key_id --profile natdanai@carro.co
      - aws configure set aws_secret_access_key $aws_secret-access-key --profile natdanai@carro.co
      - cat ~/.aws/credentials 